apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api-deployment
  labels:
    app: books-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
      - name: books-api
        image: keler1024/studying:books-rest-api
        ports:
        - containerPort: 8081
        env:
        - name: BOOKS_API_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: BOOKS_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: BOOKS_API_DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: books-api-service
spec:
  type: NodePort
  selector:
    app: books-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100